# Generated by Django 5.1 on 2026-06-30 20:00

import secretshare.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='The secret content to share.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=secretshare.models.default_expiry, help_text='Secret becomes invalid after this time even if never viewed.')),
                ('viewed_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
        ),
    ]
