# Generated by Django 5.1.5 on 2025-02-07 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notification',
            field=models.BooleanField(default=True, verbose_name='Receive Email Notification'),
        ),
    ]
