# Generated by Django 5.1.5 on 2025-02-07 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
