# Generated by Django 5.1.6 on 2025-02-10 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleusecode',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='singleusecode',
            name='user',
        ),
        migrations.DeleteModel(
            name='AccessList',
        ),
        migrations.DeleteModel(
            name='SingleUseCode',
        ),
    ]
