# Generated by Django 5.1.6 on 2025-02-10 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='description',
            field=models.TextField(),
        ),
    ]
